- name: mysql server configuration
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enable service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: Set root user password
    ansible.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: database.awsdevsecops.online
    register: mysql_result



    
